const ListingsActionTypes = {
    FETCH_LISTINGS_START: 'FETCH_LISTINGS_START',
    FETCH_LISTINGS_SUCCESS: 'FETCH_LISTINGS_SUCCESS',
    FETCH_LISTINGS_FAILURE: 'FETCH_LISTINGS_FAILURE'
};

export default ListingsActionTypes;