const ListingsActionTypes = {
    FETCH_LISTINGS_START: 'FETCH_LISTINGS_START',
    FETCH_LISTINGS_SUCCESS: 'FETCH_LISTINGS_SUCCESS',
    FETCH_LISTINGS_FAILURE: 'FETCH_LISTINGS_FAILURE',
    STORE_INPUT: 'STORE_INPUT',
    STORE_API_INPUT: 'STORE_API_INPUT'
};

export default ListingsActionTypes;